// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_mixed = new UnifiedLeaderboard("Mixed",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI8471xKQHEAIQAg"
#else
            "Mixed"
#endif
            );

        public static UnifiedLeaderboard Mixed
        {
            get { return s_mixed; }
        }

        private static readonly UnifiedLeaderboard s_addition = new UnifiedLeaderboard("Addition",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI8471xKQHEAIQBA"
#else
            "Addition"
#endif
            );

        public static UnifiedLeaderboard Addition
        {
            get { return s_addition; }
        }

        private static readonly UnifiedLeaderboard s_subtraction = new UnifiedLeaderboard("Subtraction",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI8471xKQHEAIQBQ"
#else
            "Subtraction"
#endif
            );

        public static UnifiedLeaderboard Subtraction
        {
            get { return s_subtraction; }
        }

        private static readonly UnifiedLeaderboard s_multiplication = new UnifiedLeaderboard("Multiplication",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI8471xKQHEAIQBg"
#else
            "Multiplication"
#endif
            );

        public static UnifiedLeaderboard Multiplication
        {
            get { return s_multiplication; }
        }

        private static readonly UnifiedLeaderboard s_division = new UnifiedLeaderboard("Division",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI8471xKQHEAIQBw"
#else
            "Division"
#endif
            );

        public static UnifiedLeaderboard Division
        {
            get { return s_division; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "Mixed", s_mixed },
            { "Addition", s_addition },
            { "Subtraction", s_subtraction },
            { "Multiplication", s_multiplication },
            { "Division", s_division },
        };
    }
}
